# This module contains all constant values that are used throughout the project.
# ie: display information, tile sizes, coordinates, game state names..


# DISPLAY DATA
# The resolution of the game can be configured by manipulating the SCALE variable.
# Full screen can be turned on by flipping the value to 1.
SCALE = 1  # 1 = 480x270 : 2 = 960x540: 3 = 1440x810: 4 = 1920x1080 /////DO NOT GO ABOVE 4/////////
FULLSCREEN = 0
DISPLAY_WIDTH = 480 * SCALE
DISPLAY_HEIGHT = 270 * SCALE
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)
DISPLAY_TOP = 0
DISPLAY_BOTTOM = DISPLAY_HEIGHT
DISPLAY_LEFT = 0
DISPLAY_RIGHT = DISPLAY_WIDTH
DISPLAY_TOP_LEFT = (0, 0)
DISPLAY_TOP_RIGHT = (DISPLAY_WIDTH, 0)
DISPLAY_BOTTOM_LEFT = ()
DISPLAY_BOTTOM_RIGHT = ()
DISPLAY_WIDTH_CENTER = DISPLAY_WIDTH // 2
DISPLAY_HEIGHT_CENTER = DISPLAY_HEIGHT // 2
DISPLAY_CENTER = (DISPLAY_WIDTH_CENTER, DISPLAY_HEIGHT_CENTER)

# FPS AND TIME DATA
FPS = 60

# TILE DATA
SMALL_TILE_WIDTH = 8 * SCALE
SMALL_TILE_HEIGHT = 8 * SCALE
SMALL_TILE_SIZE = (SMALL_TILE_WIDTH, SMALL_TILE_HEIGHT)
MEDIUM_TILE_WIDTH = 16 * SCALE
MEDIUM_TILE_HEIGHT = 16 * SCALE
MEDIUM_TILE_SIZE = (MEDIUM_TILE_WIDTH, MEDIUM_TILE_HEIGHT)
LARGE_TILE_WIDTH = 32 * SCALE
LARGE_TILE_HEIGHT = 32 * SCALE
LARGE_TILE_SIZE = (LARGE_TILE_WIDTH, LARGE_TILE_HEIGHT)

# GAME STATES / SCENES
SPLASH_SCREEN = "SPLASH_SCREEN"
LOAD_SCREEN = "LOAD_SCREEN"
MAIN_MENU = "MAIN_MENU"
CHARACTER_SELECT = "CHARACTER_SELECT"
LEVEL = "LEVEL"
GAME_OVER = "GAME_OVER"
STARTING_STATE = SPLASH_SCREEN
STATE_LIST = [SPLASH_SCREEN,
              LOAD_SCREEN,
              MAIN_MENU,
              CHARACTER_SELECT,
              LEVEL,
              GAME_OVER]


